### ISSUE TITLE
image_plot_tools.py  and contrast (image shakes)

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#10]
Hello,

Will testing out application we found a problem when changing the contrast.
You can reproduce the problem with the image_plot_tools test.
Juste start the test and activate the contrast tool.
then change the contrast and you will see that the plot  is shacking.

Cheers

**Comment by PierreRaybaut** [comment]
Should be fixed following this commit: https://github.com/PierreRaybaut/python-qwt/commit/7233d416e1f678068cab23403e6aa31937f5208d

(This is a _python-qwt_ bug, not a _guiqwt_ bug)
