### ISSUE TITLE
TrImageItem will emit a signal when the image is moved but not when resized

### ISSUE THREAD

**Issue by RussBerg** [PierreRaybaut/guiqwt#104]
Example situation:
UI displays specifics about the current _TrImageItem_ in the plotter such as 
center (X,Y), number of pixels (X,Y), range in microns (X,Y) and the size of each pixel for X and Y in microns

If the parent of the plot wants to wants to update these parameters if the image is moved or resized they can do so by handling the **SIG_ITEM_MOVED** signal, but this is only if the image item is moved, if the _TrImageItem_ is resized no signal is emitted.

here is a visual of what I am talking about, resizing the pattern image in the center of the plot should emit a signal indicating the change, that signal handler then updates the scan parameters on the UI.
![image](https://github.com/PierreRaybaut/guiqwt/assets/4698891/a6dd3d77-c013-4cb8-bf78-144a97acc859)

**Comment by PierreRaybaut** [comment]
Fixed by https://github.com/PierreRaybaut/guiqwt/commit/ebfe7c38c9501d66d3e5ec71598a1595c368a678
