### ISSUE TITLE
[4.4.1] how to run tests in UNATTENDED mode like guidata

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#110]
Hello, I got a bug report from Debian, requesting to add autopkgtest in order to test guiqwt integration.

So my question is:

what is the proper way to run guiqwt test ?

**Comment by PierreRaybaut** [comment]
Currently there is no way to run tests in unattended mode like [guidata](https://github.com/Codra-Ingenierie-Informatique/guidata). It would require a lot of work... which has already been done in [plotpy](https://github.com/Codra-Ingenierie-Informatique/plotpy)! (the next major version of guiqwt...)

So, I understand the request, and the official answer is that it will soon be available with [plotpy](https://github.com/Codra-Ingenierie-Informatique/plotpy)! (I'm planning the first public release for september)

**Comment by PierreRaybaut** [comment]
See [here](https://github.com/Codra-Ingenierie-Informatique/plotpy/actions/runs/5693614780/job/15433078727) for an overview of the automated test suite.
