### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by beenje** [PierreRaybaut/guiqwt#112]
Hello!

Trying to build guiqwt with Python 3.12 on conda-forge is [failing](https://github.com/conda-forge/guiqwt-feedstock/pull/36) with `ModuleNotFoundError: No module named 'numpy.distutils'`

`numpy.distutils` has been deprecated in numpy 1.23.0 and removed in Python 3.12.
There are some migration advices [here](https://numpy.org/devdocs/reference/distutils_status_migration.html).

**Comment by PierreRaybaut** [comment]
Hi,

Thanks a lot for the feedback.
I'll take a look at it as soon as I can.

Meanwhile, FYI, the forthcoming PlotPy V2 library - guiqwt replacement - is already ready for Python 3.12:
https://github.com/PlotPyStack/plotpy/actions/runs/6579866010/job/17876637344

**Comment by beenje** [comment]
Thanks for the quick fix!
