### ISSUE TITLE
traits.hpp license informations

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#12]
Hello Pierre,

you added  some lgpl-2.1 informations in the traits.hpp file.

I looked at the lgp-2.1 snipste available in Debian and this snipset  contain the (at your opinion)  any later version.

can you confirm that that the version used by the upstream author of the asm code is LGPL-2.1 strict.

This package is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version. This package is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this package; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA On Debian systems, the complete text of the GNU Lesser General Public License can be found in `/usr/share/common-licenses/LGPL-2.1'.

**Comment by PierreRaybaut** [comment]
FYI, the **two lines** which are concerned by those specific license terms are [line 45](https://github.com/PierreRaybaut/guiqwt/blob/master/src/traits.hpp#L45) and [line 60](https://github.com/PierreRaybaut/guiqwt/blob/master/src/traits.hpp#L60) of [traits.hpp](https://github.com/PierreRaybaut/guiqwt/blob/master/src/traits.hpp).

I can confirm that the license terms are identical to the one you are referring to: the [latest package of SpanDSP](http://www.soft-switch.org/downloads/spandsp/spandsp-0.0.6.tar.gz) (the project from which this code snippet was taken from) is including the text "version 2.1 of the License, or (at your option) any later version.".
