### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#13]
picca@mordor:~/Debian/guiqwt/guiqwt$ debuild
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: paquet source guiqwt
dpkg-buildpackage: version source 2.4.0~b3-1~exp1
dpkg-buildpackage: distribution source experimental
dpkg-buildpackage: source changé par Picca Frédéric-Emmanuel <picca@debian.org>
 dpkg-source --before-build guiqwt
dpkg-buildpackage: architecture hôte i386
dpkg-source: info: utilisation des options depuis guiqwt/debian/source/local-options : --unapply-patches
 fakeroot debian/rules clean
dh clean --with python2,python3,sphinxdoc --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:170: python2.7 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    if _bld and 'mingw32' in _bld.get('compiler'):
TypeError: argument of type 'NoneType' is not iterable
E: pybuild pybuild:262: clean: plugin distutils failed with: exit code=1: python2.7 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 2.7 --dir . returned exit code 13

**Comment by PierreRaybaut** [comment]
Fixed.

Thanks @picca for reporting this... any other blocking issue?
 If not, I'll upload the v2.4.0b4 release fixing this issue.

**Comment by picca** [comment]
I did not check but i will tell you :) once release ;)

**Comment by PierreRaybaut** [comment]
I've just uploaded v2.4.0b4.
