### ISSUE TITLE
replot method is much slower in Python 3.4

### ISSUE THREAD

**Issue by PierreRaybaut** [PierreRaybaut/guiqwt#28]
Issue originally submitted here: https://code.google.com/p/guiqwt/issues/detail?id=62

Reported by petebachant, Nov 20, 2014

*What steps will reproduce the problem?*
1. Create a PyQt4 app with a plot widget that continuously replots data
2. Run in Python 2.7
3. Run in Python 3.4

*What is the expected output? What do you see instead?*
The entire main window becomes very laggy on Python 3.4. Upon profiling it seems in Python 3.4 the replot method takes about twice as long, which is killing performance. 

*What version of the product are you using? On what operating system?*
The latest version in WinPython 2.7.8.3 and 3.4.2.2.

**Comment by PierreRaybaut** [comment]
@petebachant: I'm progressively migrating "issues" that were not addressed from the old GoogleCode site. Is this one still valid?

**Comment by petebachant** [comment]
I haven't tried running on Python 3 since then, so I don't know. I will give it a try when I get a chance.
