### ISSUE TITLE
intrin.h is missing in the sources

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#44]
Hello, it seems that I can not build guiqwt.

src/traits.hpp:30:20: fatal error: intrin.h: No such file or directory
 #include <intrin.h>
                    ^

**Comment by PierreRaybaut** [comment]
Not tested though... but it should work!

**Comment by PierreRaybaut** [comment]
(can you test it?)

**Comment by picca** [comment]
Yes it works :)
