### ISSUE TITLE
curious bottom on the histogram example

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#45]
![histogram_bottom_is_no_flat](https://cloud.githubusercontent.com/assets/4312421/11015969/f7681600-8572-11e5-95e1-11292ab317b5.GIF)

Wipython 3.4.3.7b0 , guiqwt of today morning, compiled with mingwpy

**Comment by PierreRaybaut** [comment]
This is related to [this PythonQwt Issue](https://github.com/PierreRaybaut/PythonQwt/issues/28). It is fixed with latest PythonQwt revision.

**Comment by stonebig** [comment]
ok, checked on my pc
