### ISSUE TITLE
would it be possible to have a guiqwt-3.0.0rc2-cp35-none-win_amd64.whl (md5) ?

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#52]
trying to assemble a WinPython3.5, I fall on this problem.

**Comment by PierreRaybaut** [comment]
I guess so. I admit that I haven't been studying the Python 3.5 specificities: maybe there are differences in the language itself or in the way it deals with C++ extensions, I really don't know. But if there aren't, then it's "just" a matter of time: I haven't installed or tried Python 3.5 yet and I certainly don't have a full VS2015 build tool chain installed yet. Maybe I could take a look at it this weekend and get back to you.
________________________________
De : stonebig<mailto:notifications@github.com>
Envoyé : ‎11/‎11/‎2015 19:28
À : PierreRaybaut/guiqwt<mailto:guiqwt@noreply.github.com>
Objet : [guiqwt] would it be possible to have a guiqwt-3.0.0rc2-cp35-none-win_amd64.whl (md5) ? (#52)

trying to assemble a WinPython3.5, I fall on this problem.

---
Reply to this email directly or view it on GitHub:
https://github.com/PierreRaybaut/guiqwt/issues/52

**Comment by stonebig** [comment]
Maybe Christoph will simply generate it for you when you will be 3.0.0 final.

**Comment by PierreRaybaut** [comment]
By the way, I think that the final release will be ready for this weekend: there is no more opened blocking issue!

@picca: Any Debian-related request before final release? Anyway, there is still v3.0.1 to fix issues very quickly (by experience, my vX.0.0 versions do not last long 😊).
________________________________
De : stonebig<mailto:notifications@github.com>
Envoyé : ‎11/‎11/‎2015 23:00
À : PierreRaybaut/guiqwt<mailto:guiqwt@noreply.github.com>
Cc : Pierre Raybaut<mailto:pierre.raybaut@gmail.com>
Objet : Re: [guiqwt] would it be possible to have a guiqwt-3.0.0rc2-cp35-none-win_amd64.whl (md5) ? (#52)

Maybe Christoph will simply generate it for you when you will be 3.0.0 final.


---

**Comment by PierreRaybaut** [comment]
Done:
https://pypi.python.org/packages/3.5/g/guiqwt/guiqwt-3.0.0rc2-cp35-none-win32.whl
https://pypi.python.org/packages/3.5/g/guiqwt/guiqwt-3.0.0rc2-cp35-none-win_amd64.whl

**Comment by picca** [comment]
Hello, Sorry for answering so late. I am just wondering if the full stack is compatible with the  2.3.5 version of spyder.

The last time I checkd I got an error due to the #API1 #API2 mismatch

**Comment by stonebig** [comment]
Thanks Pierre !

**Comment by stonebig** [comment]
I get a bad python failure "Python a sessé de fonctionnerr" when leaving the "qtdesigner" example, not a real problem, but you may have a look
