### ISSUE TITLE
QEvent AttributeError (guiqwt v2.3.1)

### ISSUE THREAD

**Issue by Foreade** [PierreRaybaut/guiqwt#54]
Hi,

I have a problem with guiqwt 2.3.1, that some of you might have encountered. First of all, installing it worked well. Now I have a running version for which almost all guiqwt-tests work well. Only for dialogues and similar things, I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/guiqwt/events.py", line 167, in eventFilter
    if match(event):
  File "/usr/lib/python2.7/dist-packages/guiqwt/events.py", line 131, in __call__
    event.buttons() == Qt.NoButton):
AttributeError: 'QEvent' object has no attribute 'buttons'

over and over again (presumably as QEvents is triggered). And ideas as to what might be going on?

Thanks!

**Comment by Foreade** [comment]
Hi again,

I just solved the problem by downgrading SIP to 4.15 and recompiling. Maybe this helps whoever encounters the same problem.

Best

**Comment by PierreRaybaut** [comment]
Thanks for the feedback.

FYI, from version 3, `guiqwt` is no longer based on `PyQwt` (but on `PythonQwt` which is pure Python) and the compilation step is no longer needed.
