### ISSUE TITLE
"cannot convert  float Nan to integer" error in pcolor test

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#6]
on Qt5 Python3.4-64 windows, the pcolor test terminates with an error when we click on the fan (manual air fan?)

![guiqwt_pcolor_bug](https://cloud.githubusercontent.com/assets/4312421/9446234/bc3567b2-4a90-11e5-8930-f757642197e0.GIF)

**Comment by PierreRaybaut** [comment]
Will be fixed in next `python-qwt` release:
https://github.com/PierreRaybaut/python-qwt/commit/c66e06188cf30ce27b56e218740d232c638f2204
