### ISSUE TITLE
X Axis in datetime format

### ISSUE THREAD

**Issue by MikeKilo** [PierreRaybaut/guiqwt#65]
I'm having hard time implementing X axis in datetime format.
I am using seconds from epoch / GPS time as X axis, and want to present it in time of day format.
Tried this:
[https://groups.google.com/forum/#!msg/guidata_guiqwt/3iVWxw1oiRY/Gbe6nlAPvWIJ](url)
But changes in dependencies keep raising exceptions.

Any ideas?

**Comment by PierreRaybaut** [comment]
See this new example for a X-axis with time data:
https://github.com/PierreRaybaut/guiqwt/blob/master/guiqwt/tests/plot_timecurve.py
