### ISSUE TITLE
32bit wheel on PyPI includes 64bit libraries

### ISSUE THREAD

**Issue by pa-eidam** [PierreRaybaut/guiqwt#69]
Affected wheel: guiqwt-3.0.3-cp35-cp35m-win32.whl
Libraries: _scaler.cp35-win_amd64.pyd, histogram2d.cp35-win_amd64.pyd, mandelbrot.cp35-win_amd64.pyd
Source: PyPI (pypi.python.org/pypi/guiqwt)

**Comment by PierreRaybaut** [comment]
Fixed - duplicate of issue #88
