### ISSUE TITLE
Pages in online documentation missing

### ISSUE THREAD

**Issue by titusjan** [PierreRaybaut/guiqwt#71]
A few pages seem to be missing from the reference in the online documentation at http://pythonhosted.org/guiqwt/reference/index.html

When I download the source and generate the documentation myself (with `sphinx-build -b htmlhelp doc doctmp`) it includes pages on the `guiqwt.plot` and `guiqwt.builder` modules. The corresponding online URLs lead to empty pages (e.g. http://pythonhosted.org/guiqwt/reference/builder.html). 

These topics are crucial when learning about `guiqwt`. There may be more pages missing, I didn't to an extensive check. Please update the online documentation.

**Comment by PierreRaybaut** [comment]
Everything is now available on readthedocs:
https://guiqwt.readthedocs.io/en/latest/index.html
