### ISSUE TITLE
Issue with pyqt5 and spydererlib

### ISSUE THREAD

**Issue by JulienNic0las** [PierreRaybaut/guiqwt#72]
Hi,

After a fresh install of guiqwt (so version 3.0.3 via pip) on Anaconda 3, I cannot run tests example:

`from guiqwt import tests
tests.run()

>>>assert os.environ['QT_API'] in ('pyqt', 'pyside')
>>>AssertionError:`

I can provide a full stacktrace of the error message at request. I understand that

**Comment by PierreRaybaut** [comment]
Duplicate of #73
