### ISSUE TITLE
Issue with pyqt5 and spydeerlib

### ISSUE THREAD

**Issue by JulienNic0las** [PierreRaybaut/guiqwt#73]
Hi,

After a fresh install of guiqwt (so version 3.0.3 via pip) on Anaconda 3, I cannot run tests example:

```python
from guiqwt import tests
tests.run()

>>>assert os.environ['QT_API'] in ('pyqt', 'pyside')
>>>AssertionError:
```

I can provide a full stacktrace of the error message at request. I understand that this message is rather related to spyderlib as it seems that the run test is calling `spyderlib.qt` which raise the assertion error. Looking inside the `qt` module of spyderlib version 2.3.9 (provided by Anaconda bundle) it seems that only qt4 is supported.

Julien

**Comment by PierreRaybaut** [comment]
This should be fixed with recent compatibility with QtPy 2.0 (guiqwt v4)
