### ISSUE TITLE
Axis title not updated until I resize dialog 

### ISSUE THREAD

**Issue by cpascual** [PierreRaybaut/guiqwt#76]
The problem can be reproduced by:
1- runing the image.py example
2- clicking on the "Axes Styles" button
3- changing the title of the left axis
4- closing the dialog (now the title is correctly updated)
5 - repeat steps 2, 3 and 4 (now the title is **not** updated)
6- resize the dialog (now the title is updated)

**Comment by PierreRaybaut** [comment]
Fixed in guiqwt v4
