### ISSUE TITLE
How to update data realtime from another python thread

### ISSUE THREAD

**Issue by FredericLeuba** [PierreRaybaut/guiqwt#77]
Hello,

Thanks for this great package.
I'm having difficulty finding how to update curve data on a periodic basis to display realtime data.
Calling set_data() tells me I'm not in the right thread.
My knowledge is too limited to go further, and I cannot find any clear and straight example to do so.
I would be very graceful to get some hints about that issue.

Best regards
Fred

**Comment by PierreRaybaut** [comment]
When updating from another thread, you will have to use the signal/slot features from Qt. This is not specific to guiqwt, this is only related to the fact that you are trying to call directly a method from an object in another thread which is not allowed. If you connect a signal to the method you are trying to call, it will work.
