### ISSUE TITLE
compatibility for upcoming PySide2-5.11 preview

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#78]
After 2 years of brewing, PySide2-5.11 will reach preview status in may 2018, with:
- full support per the Qt Company,
- full API support at release time of Qt versions.

Would it be possible to have PySide2 compatibility for that may 2018 milestone ?
(QtPy, vendored or not,  being a possible intermediate layer)

see http://blog.qt.io/blog/category/qt-for-python/

for PySide2 bug tracker, see https://wiki.qt.io/Qt_for_Python

**Comment by PierreRaybaut** [comment]
I think it's now outdated. Sorry for the delay.
