### ISSUE TITLE
problem with guiqwt when launching an ImageWindow

### ISSUE THREAD

**Issue by gprevot** [PierreRaybaut/guiqwt#80]
I have a problem when launching an ImageWindow with the following code:

from guiqwt.plot import ImageWindow
from guidata import qapplication
_app = qapplication()
win = ImageWindow(toolbar=True, options={"show_contrast":True,"show_xsection":True})
win.show()
_app.exec_()

This occurs only with "show_xsection" option (not with show_ysection") and not with ImageDialog

The window is constructed but the app crash when trying to show it:

Nom d’événement de problème:	APPCRASH
  Nom de l’application:	python.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	4f84a6c8
  Nom du module par défaut:	QtCore4.dll
  Version du module par défaut:	4.8.3.0
  Horodateur du module par défaut:	505d8399
  Code de l’exception:	c0000005
  Décalage de l’exception:	000f0543
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	0a9e
  Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
  Information supplémentaire n° 3:	0a9e
  Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789

I use python 2.7, windows 7 pro

best regards

**Comment by PierreRaybaut** [comment]
Duplicate with #108
