### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Svislar** [PierreRaybaut/guiqwt#83]
Hi,

When installing guiqwt (pip/windows)  I get ModuleNotFoundError: No module named 'sip'.
I installed guidata 1.7.5 since if I install 1.7.6 I get the same error when installing it.
Any suggestion how to solve the problem?

Regards

**Comment by RaeesKhan65** [comment]
I'm having the same issue !

**Comment by PierreRaybaut** [comment]
This should be solved with recent packages.
Please comment this issue if not.
Thanks.
