### ISSUE TITLE
Python 3.10 support ?

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#87]
seems not simple

**Comment by PierreRaybaut** [comment]
Fixed since v4.0.1:
https://github.com/PierreRaybaut/guiqwt/releases/tag/v4.0.1

**Comment by stonebig** [comment]
It works ! Only minor issue is that QtDesigner.py is not working for PySide6/Python-3.10, may need leg work in QtPy.

![image](https://user-images.githubusercontent.com/4312421/147557033-9369addf-babe-4a18-b8d5-f08b922bc85f.png)

**Comment by PierreRaybaut** [comment]
Yes I know about that remaining compatibility issue with QtDesigner plugin: I've intentionally closed my eyes on this issue, I'll solve this as soon as I can.
