### ISSUE TITLE
Image visualization: should first pixel be centered at (0,0)?

### ISSUE THREAD

**Issue by PierreRaybaut** [PierreRaybaut/guiqwt#90]
In camera imaging software, pixels are always centered at their position. For example, the first image pixel (top-left corner) is centered at (0,0). In guiqwt, this pixel is not centered at (0,0): the top-left corner of this pixel is at (0,0).

**Comment by ldo** [comment]
Pixels don’t have “corners”. Pixels are not little squares. In ideal sampling, pixels are points.

**Comment by PierreRaybaut** [comment]
But pixels are not in indivisible in image processing. So this is about how we handle subpixels, for example when zooming in (or when handling images with binning other than 1x1).

So, pixels do have corners, from a certain point of view (with the necessary language précautions).

**Comment by ldo** [comment]
Resampling a set of pixels produces another set of pixels. The original samples are points, the new ones are points, too.

**Comment by PierreRaybaut** [comment]
Yes but as long as there will be subpixel measurements, there will be people that ask me where is the pixel origin, formerly either at its center or at its top left corner (the latter being a non intuitive answer, unfortunately for me: because it would require some work to properly implement this in guiqwt). And I can't simply answer them a Jedi-style "there is no corner, there is no center,  there's only a pixel" 😁.

**Comment by ldo** [comment]
It doesn’t have to be <s>Jedi</s> Zen-style; just point them at [Alvy Ray Smith](http://alvyray.com/Memos/MemosCG.htm#PixelIsNotSquare) if they want more of an answer. He knows more about it than you or I.
